"""Simülasyon, kupon önizlemesi ve performans — saf hesap, ağa çıkmaz.

Simülasyon motorunun işi indirim hesaplamak DEĞİL, kuralın yanlış yazıldığını
yazmadan önce göstermektir: koşul hiç tutmuyor, iki kampanya üst üste biniyor,
indirim sepetten büyük. Testler bu üç soruyu sorar.
"""

from __future__ import annotations

import random
from typing import Any

from store_promotions_backend import analytics

BUGUN = "2026-08-13"


def kural(**over: Any) -> dict[str, Any]:
    """Simülasyonun okuduğu ekran modeli (cart_rule_detail çıktısı biçiminde)."""
    base: dict[str, Any] = {
        "id": 1, "name": "Kural", "status": "active", "statusLabel": "Aktif",
        "couponType": "none", "code": "", "autoGenerated": False,
        "conditionType": "all", "conditions": [],
        "action": {"kind": "by_percent", "value": 10, "maxDiscount": 0, "freeShipping": False,
                   "step": 0, "quantity": 0},
        "limits": {"perCoupon": 0, "perCustomer": 0, "endOtherRules": False, "priority": 0},
        "usage": {"used": 0, "limit": 0, "ratio": None, "exhausted": False, "label": "0/sınırsız"},
        "channels": [], "customerGroups": [], "priority": 0, "freeShipping": False,
    }
    for key, value in over.items():
        if isinstance(value, dict) and isinstance(base.get(key), dict):
            base[key] = {**base[key], **value}
        else:
            base[key] = value
    return base


def sepet(*items: dict[str, Any], **over: Any) -> dict[str, Any]:
    cart = {"items": list(items) or [{"name": "Kalem", "price": 10000, "qty": 2,
                                      "productId": 5, "categoryIds": [4]}],
            "shipping": 3000, "paymentMethod": "cashondelivery", "customerGroupId": 2,
            "channelId": 1, "firstOrder": False}
    cart.update(over)
    return cart


# ============================================================== temel hesap

def test_yuzde_indirim_sepet_toplamindan_dusulur() -> None:
    result = analytics.simulate(sepet(), [kural()], today=BUGUN)
    assert result["subtotal"] == 20000
    assert result["discount"] == 2000
    assert result["payable"] == 20000 - 2000 + 3000


def test_yuzde_hesabi_kurus_kaybettirmez() -> None:
    # 2.943,00 ₺ × %30: `int(294300 * 0.3)` 88289 verir (float 88289.99999…),
    # doğrusu 88290. Bir kuruşluk sapma binlerce siparişte gözle görünür.
    result = analytics.simulate(
        sepet({"name": "X", "price": 294300, "qty": 1, "productId": 5, "categoryIds": []}),
        [kural(action={"kind": "by_percent", "value": 30})], today=BUGUN)
    assert result["discount"] == 88290


def test_ucretsiz_kargo_kargo_bedelini_sifirlar() -> None:
    result = analytics.simulate(sepet(), [kural(action={"freeShipping": True})], today=BUGUN)
    assert result["freeShipping"] is True
    assert result["payable"] == 20000 - 2000


def test_indirim_sepetten_buyuk_olamaz() -> None:
    result = analytics.simulate(sepet(), [kural(action={"kind": "cart_fixed", "value": 999999})],
                                today=BUGUN)
    assert result["discount"] == 20000
    assert result["payable"] == 3000, "eksi ödeme üretilmez"


def test_ust_sinir_yuzde_indirimi_kirpiyor() -> None:
    result = analytics.simulate(
        sepet(), [kural(action={"kind": "by_percent", "value": 50, "maxDiscount": 1500})],
        today=BUGUN)
    assert result["discount"] == 1500
    assert "üst sınır" in result["applied"][0]["note"]


def test_x_al_y_ode_en_ucuz_kalemleri_bedava_yapar() -> None:
    cart = sepet({"name": "Ucuz", "price": 1000, "qty": 2, "productId": 1, "categoryIds": []},
                 {"name": "Pahalı", "price": 5000, "qty": 1, "productId": 2, "categoryIds": []})
    result = analytics.simulate(
        cart, [kural(action={"kind": "buy_x_get_y", "value": 0, "step": 2, "quantity": 1})],
        today=BUGUN)
    # 3 adet, 2 al 1 bedava → 1 adet bedava, en ucuz olan 10,00 ₺.
    assert result["discount"] == 1000


# ================================================================ koşullar

def test_tutmayan_kosul_kurali_uygulatmaz_ve_nedenini_soyler() -> None:
    rule = kural(conditions=[{"kind": "subtotal", "operator": ">=", "value": 50000}])
    result = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert result["discount"] == 0
    assert "sepet tutarı" in result["skipped"][0]["reason"]


def test_veya_kipinde_tek_kosulun_tutmasi_yeter() -> None:
    rule = kural(conditionType="any", conditions=[
        {"kind": "subtotal", "operator": ">=", "value": 50000},
        {"kind": "itemsQty", "operator": ">=", "value": 2},
    ])
    result = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert result["discount"] == 2000


def test_kategori_kosulu_yalniz_eslesen_kalemlere_indirim_uygular() -> None:
    cart = sepet({"name": "Kitap", "price": 10000, "qty": 1, "productId": 1, "categoryIds": [4]},
                 {"name": "Kalem", "price": 10000, "qty": 1, "productId": 2, "categoryIds": [9]})
    rule = kural(conditions=[{"kind": "category", "operator": "{}", "value": [4]}])
    result = analytics.simulate(cart, [rule], today=BUGUN)
    # Yalnız kitap indirime girer: %10 × 100,00 ₺ = 10,00 ₺
    assert result["discount"] == 1000
    assert result["applied"][0]["items"] == 1


def test_ayni_urunun_iki_satiri_tek_satir_sayilmaz() -> None:
    cart = sepet({"name": "Kitap", "price": 10000, "qty": 1, "productId": 1, "categoryIds": [4]},
                 {"name": "Kitap", "price": 10000, "qty": 1, "productId": 1, "categoryIds": [4]})
    rule = kural(conditions=[{"kind": "product", "operator": "()", "value": [1]}])
    result = analytics.simulate(cart, [rule], today=BUGUN)
    assert result["discount"] == 2000
    assert result["applied"][0]["items"] == 2


def test_odeme_yontemi_kosulu_esitsizlikle_de_calisir() -> None:
    rule = kural(conditions=[{"kind": "payment", "operator": "!=", "value": "cashondelivery"}])
    result = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert result["discount"] == 0
    assert "ödeme yöntemi" in result["skipped"][0]["reason"]


# ============================================================== kapı testleri

def test_yayinda_olmayan_kural_hesaba_girmez() -> None:
    rule = kural(status="paused", statusLabel="Duraklatıldı")
    result = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert result["discount"] == 0
    assert "Duraklatıldı" in result["skipped"][0]["reason"]


def test_kuponlu_kural_kod_girilmeden_uygulanmaz() -> None:
    rule = kural(couponType="specific", code="EYLUL")
    bos = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert bos["discount"] == 0
    assert "kupon kodu" in bos["skipped"][0]["reason"]

    dolu = analytics.simulate(sepet(), [rule], coupon="eylul", today=BUGUN)
    assert dolu["discount"] == 2000, "kod büyük/küçük harf duyarsız eşleşir"


def test_musteri_grubu_disindaki_sepete_indirim_dusmez() -> None:
    rule = kural(customerGroups=[3])
    result = analytics.simulate(sepet(customerGroupId=2), [rule], today=BUGUN)
    assert "müşteri grubu" in result["skipped"][0]["reason"]


def test_limiti_dolmus_kural_uygulanmaz() -> None:
    rule = kural(usage={"used": 100, "limit": 100, "exhausted": True, "label": "100/100"})
    result = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert "limiti dolmuş" in result["skipped"][0]["reason"]


# ======================================================== kural zinciri

def test_oncelik_sirasi_uygulanir_ve_zincir_durdurulabilir() -> None:
    ilk = kural(id=1, name="Önce", limits={"priority": 1, "endOtherRules": True})
    sonra = kural(id=2, name="Sonra", limits={"priority": 5},
                  action={"kind": "cart_fixed", "value": 5000})
    result = analytics.simulate(sepet(), [sonra, ilk], today=BUGUN)
    assert [row["name"] for row in result["applied"]] == ["Önce"]
    assert result["chainStopped"] == "Önce"
    assert "zinciri durdurdu" in result["skipped"][0]["reason"]


def test_zincir_durmazsa_iki_kural_ust_uste_biner() -> None:
    ilk = kural(id=1, name="Yüzde", limits={"priority": 1})
    sonra = kural(id=2, name="Sabit", limits={"priority": 2},
                  action={"kind": "cart_fixed", "value": 5000})
    result = analytics.simulate(sepet(), [ilk, sonra], today=BUGUN)
    assert result["discount"] == 2000 + 5000
    assert len(result["applied"]) == 2


def test_indirim_cikmayan_kural_uygulandi_sayilmaz() -> None:
    rule = kural(action={"kind": "by_percent", "value": 0})
    result = analytics.simulate(sepet(), [rule], today=BUGUN)
    assert result["applied"] == []
    assert "indirim çıkmadı" in result["skipped"][0]["reason"]


# ============================================================ kupon üreteci

def test_kupon_ornekleri_karisan_harfleri_kullanmaz() -> None:
    codes = analytics.code_preview(prefix="BBD-", length=10, count=20,
                                   rng=random.Random(7))
    assert all(code.startswith("BBD-") and len(code) == 14 for code in codes)
    body = "".join(code[4:] for code in codes)
    assert not set(body) & set(analytics.UNSAFE), "0/O ve 1/I/L kodda bulunmaz"


def test_sayisal_bicimde_yalniz_rakam_uretilir() -> None:
    codes = analytics.code_preview(length=6, fmt="numeric", count=5, rng=random.Random(3))
    assert all(code.isdigit() for code in codes)


def test_ureteç_sinirlari_asilirsa_anlasilir_hata_doner() -> None:
    problem = analytics.generator_error(count=99_999, length=8, min_length=6, max_length=24,
                                        max_count=5000)
    assert "Adet 1 ile 5000" in problem
    assert analytics.generator_error(count=10, length=8, min_length=6, max_length=24,
                                     max_count=5000) == ""


def test_uretimden_sonra_yalniz_yeni_kodlar_ayiklanir() -> None:
    before = [{"code": "A1"}, {"code": "A2"}]
    after = [{"code": "A1"}, {"code": "A2"}, {"code": "B1"}, {"code": "B2"}]
    assert analytics.new_codes(before, after) == ["B1", "B2"]


# ============================================================== performans

SIPARISLER = [
    {"id": 1, "coupon_code": "EYLUL", "grand_total": "200.00", "discount_amount": "20.00",
     "status": "processing", "created_at": "2026-08-01 10:00:00"},
    {"id": 2, "coupon_code": "EYLUL", "grand_total": "100.00", "discount_amount": "10.00",
     "status": "completed", "created_at": "2026-08-05 10:00:00"},
    {"id": 3, "coupon_code": "EYLUL", "grand_total": "500.00", "discount_amount": "50.00",
     "status": "canceled", "created_at": "2026-08-06 10:00:00"},
    {"id": 4, "coupon_code": "", "grand_total": "400.00", "discount_amount": "0",
     "status": "completed", "created_at": "2026-08-07 10:00:00"},
]


def test_iptal_edilen_siparis_kampanya_cirosuna_girmez() -> None:
    result = analytics.coupon_performance(SIPARISLER)
    row = result["rows"][0]
    assert row["code"] == "EYLUL"
    assert row["orders"] == 2
    assert row["canceled"] == 1
    assert row["revenue"] == 30000          # 200 + 100 ₺, iptal olan yok sayıldı


def test_kuponlu_ve_kuponsuz_ortalama_sepet_ayri_hesaplanir() -> None:
    totals = analytics.coupon_performance(SIPARISLER)["totals"]
    assert totals["couponOrders"] == 2
    assert totals["average"] == 15000
    assert totals["plainOrders"] == 1
    assert totals["plainAverage"] == 40000


def test_kupon_koduna_kampanya_adi_eslesir() -> None:
    result = analytics.coupon_performance(
        SIPARISLER, rules=[{"code": "eylul", "name": "Eylül kampanyası"}])
    assert result["rows"][0]["rule"] == "Eylül kampanyası"


def test_ciro_sifirken_indirim_orani_tanimsizdir() -> None:
    result = analytics.coupon_performance([
        {"coupon_code": "BOS", "grand_total": "0", "discount_amount": "10.00",
         "status": "pending", "created_at": "2026-08-02"},
    ])
    assert result["rows"][0]["costRatio"] is None


def test_ilk_ve_son_kullanim_gunleri_tutulur() -> None:
    row = analytics.coupon_performance(SIPARISLER)["rows"][0]
    assert row["first"] == "2026-08-01"
    assert row["last"] == "2026-08-06"


def test_kullanim_cubuklari_en_cok_kullanilan_ustte_gelir() -> None:
    rows = analytics.rule_usage_bars([
        {"id": 1, "name": "Az", "usage": {"used": 2, "limit": 10, "label": "2/10"}},
        {"id": 2, "name": "Çok", "usage": {"used": 9, "limit": 10, "label": "9/10"}},
    ])
    assert [row["name"] for row in rows] == ["Çok", "Az"]
